### ISSUE TITLE
Capybara tests fail to run with eventmachine 1.2.0.1

### ISSUE THREAD

**Issue by faiz553** [eventmachine/eventmachine#703] opened 2016-03-18 16:08 UTC
Capybara feature tests in my project started failing a few days ago right after 1.2.0.1 was released. The first one fails with the error - 
```
RuntimeError:
       Rack application timed out during boot
```
and following tests fail with -
```
Failure/Error: Unable to find matching line from backtrace
     RuntimeError:
       no acceptor (port is in use or requires root privileges)
```

I consume eventmachine as a transitive dependency through thin(1.6.4). 
```
eventmachine (1.2.0.1)
...
thin (1.6.4)
      daemons (~> 1.0, >= 1.0.9)
      eventmachine (~> 1.0, >= 1.0.4)
      rack (~> 1.0)
```

If I lock eventmachine to 1.0.9.1, the tests run fine. Did something change in 1.2.0.1 that could be causing this?

Thank you for the help.

**Comment by tmm1** [comment] 2016-03-18 16:18
The port you are trying to use is in use by another process.

**Comment by mikeantonelli** [comment] 2016-03-18 16:50
@tmm1 The port-in-use error only occurs after the first test times out, which leads us to believe that the timeout exception isn't being handled properly -- there are two questions here:

1. What is causing the first request to timeout only after updating eventmachine?
2. Why isn't a timeout occurring on all tests, rather a timeout only once and then port-in-use errors?

**Comment by faiz553** [comment] 2016-03-18 16:53
@tmm1 As far as I can tell, it's always using a random port when running the tests and times out with the first request with different ports. And as I mentioned, it's only after consuming the latest version of eventmachine that I'm seeing these errors.

**Comment by sodabrew** [comment] 2016-03-18 18:23
I'd definitely like to help figure out why you're seeing that first error. One thing I've noticed is that some systems may try to default to IPv6 in a way that EM 1.2 now understands, whereas EM 1.0 was more limited to IPv4. Maybe your application is coming up on ::1 instead of 127.0.0.1 by default?

Googling for `Rack application timed out during boot` brings up a few mentions of Capybara, so I would also run down whether any old issues have been brought back.

**Comment by mikeantonelli** [comment] 2016-03-18 18:27
I was just doing some debugging and did find out that our timeout error is being caused by:

```
SystemCallError: #<Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 64151>
```

If I open my browser, I can access the server @ `http://localhost`, but not `http://127.0.0.1` -- so I'm guessing it has something to do with the bind address. I can set `Capybara.server_host = 'localhost'` and things work again but did EventMachine change the default bind address recently?

**Comment by sodabrew** [comment] 2016-03-18 18:31
No question then, localhost is resolving to IPv6's ::1 localhost first and then to IPv4's 127.0.0.1 localhost.

EM 1.2 does a name resolution on "localhost" and simply uses the first address it gets back from the system, whereas EM 1.0 did an explicit IPv4 lookup and so it would not have seen the IPv6 address.

Change `Capybara.server_host = '127.0.0.1'` and see if it resolves the problem.

**Comment by mikeantonelli** [comment] 2016-03-18 18:38
It doesn't solve the problem because the Thin server is being started on `localhost` explicitly by default, it looks like I'd have to configure the `RACK_ENV` in order to get it to bind to `0.0.0.0`:

https://github.com/rack/rack/blob/1.6.4/lib/rack/handler/thin.rb#L9-L10

**Comment by sodabrew** [comment] 2016-03-18 18:40
It looks like you can add a `:Host` field in the options at `Rack::Handler::Thin.run(app, options={})`.

**Comment by mikeantonelli** [comment] 2016-03-18 18:46
Thanks @sodabrew that did work:

```ruby
Rack::Handler::Thin.run(app, { :Host => '127.0.0.1', :Port => port })
```

Since it was a [transitive depenency](https://github.com/macournoyer/thin/blob/v1.6.4/thin.gemspec#L23) in a ruby gem for us, EM 1.2 was pulled automatically -- this will require a code change in multiple projects for my team. Do you think there is a worthwhile change in either `rack`, `thin` or `evenmachine`?

**Comment by sodabrew** [comment] 2016-03-18 21:27
This is a good question. I had suspected that some systems would respond to `getaddrinfo("localhost" ... AF_UNSPEC)` with ::1 ahead of 127.0.0.1. The problem isn't necessarily that EM is using IPv6 first, it's that you have something else in your stack that is using IPv4 first (or only IPv4) and they're mis-matched.

One option would be for EM to sort its `getaddrinfo` responses and choose IPv4 addresses if possible. Another option would be to call `getaddrinfo` twice, first to see if there are IPv4 addresses and if not, then query again for IPv6 addresses.

It occurs to me that you wrote:
>  I can set Capybara.server_host = 'localhost' and things work again but did EventMachine change the default bind address recently?
And perhaps this is exactly the right answer: that it is _Capybara_ that should change from a default address of `127.0.0.1` because the local machine may be trying to bias `localhost` towards `::1` and we should respect that where possible.
https://github.com/jnicklas/capybara/blob/master/lib/capybara.rb#L293-L299

**Comment by sodabrew** [comment] 2016-03-22 23:04
Capybara folks responded that changing this from 127.0.0.1 might break a lot of user tests. I think that means we'll just leave this as documentation that the two workarounds are either:

1. Change Capybara's setting `Capybara.server_host = 'localhost'`
1. Change Thin's setting `Rack::Handler::Thin.run(app, { :Host => '127.0.0.1', :Port => port })`

**Closed by sodabrew** 2016-03-22 23:04 UTC

**Comment by faiz553** [comment] 2016-03-23 01:30
Thanks for your help @sodabrew and @mikeantonelli !
