### ISSUE TITLE
EM::DNS::Resolver.socket() fails if /etc/hosts contains "invalid byte sequence in US-ASCII"

### ISSUE THREAD

**Issue by ibc** [eventmachine/eventmachine#404] opened 2013-02-19 23:15 UTC
In my /etc/hosts there is a comment (#) which contains a "ñ" symbol, so `EM::DNS::Resolver.socket()` fails in:

```
IO.readlines('/etc/hosts').each do |line|
  next if line =~ /^#/
```

A regular expression cannot contain multibyte symbols.

**Comment by sodabrew** [comment] 2015-11-04 06:27
Closing, as I cannot reproduce this on my system (Mac OS X, Ruby 2.0).

**Closed by sodabrew** 2015-11-04 06:27 UTC
