### ISSUE TITLE
Ruby 2.0.0, EventMachine 1.0.4: Assertion `nbytes > 0' failed

### ISSUE THREAD

**Issue by alexnorthsoul** [eventmachine/eventmachine#559] opened 2015-01-15 18:23 UTC
We've been facing this issue using 1.0.3 and 1.0.4

ruby: ed.cpp:1025: void ConnectionDescriptor::_WriteOutboundData(): Assertion `nbytes > 0' failed

```
# ruby -v
ruby 2.0.0p598 (2014-11-13 revision 48408) [x86_64-linux]
```

**Comment by sodabrew** [comment] 2015-01-15 20:09
Please provide a backtrace

**Comment by tmm1** [comment] 2015-01-15 20:10
Try `EM.epoll=true` before `EM.run`

**Comment by alexnorthsoul** [comment] 2015-01-15 23:38
@sodabrew, unfortunately there is no full backtrace yet.
@tmm1, thank you for hint, I'll try this within 24 hours

**Comment by sodabrew** [comment] 2015-02-04 03:57
Ping @alexnorthsoul Any luck reproducing again / or resolution with today's release?

**Comment by sodabrew** [comment] 2015-02-04 04:49
This couldn't be #51 because there's no kqueue on

**Comment by tmm1** [comment] 2015-02-10 09:36
This was probably fixed in #525

**Closed** 2015-08-03 23:05 UTC
