### ISSUE TITLE
Windows Error: Encryption not available on this event-machine

### ISSUE THREAD

**Issue by AaronMertes** [eventmachine/eventmachine#718] opened 2016-05-31 17:40 UTC
I've created a Rest API using Ruby/Rack/Thin and it works very well when I access it using http. However, if i try to access using https I continue to get the message 'Encryption not available on this event-machine'. I have installed OpenSSL and followed some advice online but nothing seems to work. Is this even possible or should I look to IIS or something else? I'm using event-machine 1.2.01. x86-mingw32, Ruby 2.0.0p648, and thin 1.6.2. Any advice or guidance you could provide would be greatly appreciated. I'm fairly new to this tech stack so I could be guilty of something stupid, my apologies in advance if that's the case.

**Comment by sodabrew** [comment] 2016-05-31 17:51
Duplicate of #689.

**Closed by sodabrew** 2016-05-31 17:51 UTC
