### ISSUE TITLE
update their dependency to rake-compiler-dock-0.6 and to add ruby-2.4 and 2.5 binary support

### ISSUE THREAD

**Issue by felicityfmn** [eventmachine/eventmachine#820] opened 2018-01-30 13:58 UTC
Could you please update your dependency and make a new x64-mingw release, please? I keep getting the error :
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'

And even though I request em/pure_ruby on my .rb file, I still get:
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5-x64-mingw32/lib/em/pure_ruby.rb:554:in `close': Bad file descriptor (Errno::EBADF)

**Comment by sodabrew** [comment] 2018-01-30 17:30
This is on my TODO list. In the mean time, you can compile locally with the Ruby DevKit and:

```
gem install --platform ruby eventmachine
```

**Comment by felicityfmn** [comment] 2018-01-31 18:10
doing this doesn't help. I still get the same error.

**Comment by sodabrew** [comment] 2018-01-31 18:13
The error indicates that you're not getting the compiled EventMachine. Do
you have the DevKit activated in your RubyInstaller installation?
https://rubyinstaller.org/downloads

That Bad File Descriptor error might be a bug in the pure ruby reactor. Can
you post a backtrace for that?

**Comment by felicityfmn** [comment] 2018-01-31 18:29
yeah I have the DevKit MSYS2 toolkit. 
this is what i get:
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5/lib/em/pure_ruby.rb:554:in `close': Bad file descriptor (Errno::EBADF)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5/lib/em/pure_ruby.rb:554:in `block in run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5/lib/em/pure_ruby.rb:554:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5/lib/em/pure_ruby.rb:554:in `ensure in run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5/lib/em/pure_ruby.rb:557:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5/lib/em/pure_ruby.rb:144:in `run_machine'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run'
        from C:/Ruby24-x64/flutterbot/play.rb:16:in `<main>'

**Comment by MSP-Greg** [comment] 2018-02-24 23:07
@felicityfmn

I've installed EM on 2.4, 2.5, & 2.6.  Or, if MSYS2 is configured correctly, it should install.

Try the following (assuming you have the msys2 openssl package):
```
gem install eventmachine --platform ruby -- --use-system-libraries --with-ssl-dir=c:/msys64/mingw64

C:\>ruby -reventmachine -e "puts EM.ssl?"  => true
```

**Comment by felipecruz91** [comment] 2018-03-02 22:12
Thanks @MSP-Greg, it works!

**Comment by BMahabir** [comment] 2018-03-22 14:42
This works in theory, but how do I tell the many users on my project that they have to enter a funky "gem install" command every time they need to reinstall/update their repo for any reason?  Also, adding 'gem 'eventmachine', :platforms => :ruby' to the Gemfile does not work, no matter what I try it always defaults to the mingw32 version.

**Comment by MSP-Greg** [comment] 2018-03-22 15:11
@stefan-kolb

Please be aware that 2.4 & 2.5 use different versions of OpenSSL.  2.4 uses the standard 1.0.2 MSYS2 package, 2.5 uses a custom 1.1.0 package.  I've always build EM with OpenSSL, so I'm not familiar with its behavior when built without it...

@BMahabir

There are two issues here, the first is the need for an updated fat binary gem, which @sodabrew responded to.  I'd help, but I need to get more familiar with building them.  On my TODO list...

Second issue is whether EM can be built.  I addressed that.

Among your 'many users', some may have MSYS2 build tools installed, some may not.  I've got `--platform ruby` in my `.gemrc` file, but I suspect I know my way around MSYS2 a bit better than many Windows Ruby users.

**Comment by MSP-Greg** [comment] 2018-03-23 02:09
@sodabrew

I gave the issue a quick look, and I think I can generate the files needed for a windows 'fat-binary' gem on Appveyor.  All the Ruby builds are available at once, one simply needs to change `ENV['PATH']`.

Seems like that would be a lot easier than cross-compiling, especially given that Ruby on windows uses two different toolsets (one for 2.3 and below, another for 2.4 and above) and three versions of OpenSSL.

Would that be helpful?  If so, what versions of Ruby (other than 2.3 thru 2.5)?

Thanks, Greg

**Comment by sodabrew** [comment] 2018-04-22 16:59
Resolved by #833

**Closed by sodabrew** 2018-04-22 16:59 UTC

**Comment by Inversion-des** [comment] 2018-05-23 07:30
>doing this doesn't help. I still get the same error.  

Probably you should delete another installed gem
`gem uninstall  eventmachine`

Select gem to uninstall:
 1. eventmachine-1.2.7
 2. eventmachine-1.2.7-x64-mingw32 — **this should be deleted**
 3. All versions

**Comment by mlt** [comment] 2018-10-26 18:48
> **this should be deleted**

The problem is that it needs to be done every time after bundle update ☹️

**Comment by soundasleep** [comment] 2018-11-08 23:37
I can confirm that you still need to uninstall eventmachine every time you do a `bundle update` on Windows. Ugh.

Not sure if there's a way to configure a Gemfile to use the ruby version of eventmachine?

**Comment by nathanvda** [comment] 2019-01-14 18:00
I had the same problem, and until a new release of `eventmachine` we will keep encountering this problem I am afraid. So I wanted to fix my `Gemfile` to make this fail-safe, and was able to do this using the gem from git/source instead: 

     gem 'eventmachine', '1.2.7', git: 'git@github.com:eventmachine/eventmachine', tag: 'v1.2.7'

Now I can just install my bundle and it will work :+1: (both on my mac dev-machine and my windows server where it needs to be deployed)

**Comment by MSP-Greg** [comment] 2019-01-14 20:17
Something like the following may work in Gemfile:
```ruby
# install ruby eventmachine
plats = Gem.platforms
Gem.platforms = %w(ruby)
Gem.install 'eventmachine'   # ? add :build_args ?
Gem.platforms = plats

gem 'eventmachine'
```

FWIW, EventMachine is running in Appveyor CI against Ruby 2.2 thru trunk/2.7, and passing all tests (there are intermittent issues).

The issues here are caused by:

1. The current EM pre-compiled gem seems to have a Ruby version constraint of ">= 0".  Hence, it will install in any Ruby version, but only work for the versions it's compiled for.

2. Even if there was a correct constraint, Bundler uses RubyGems.  Currently, RubyGems ignores 'Ruby version constraints' when selecting which gem to install, but, it does take them into account when actually installing the gem.  So, even if the gemspec was correct, Bundler can't install it.  Hence, the work-around above, which is similar to using `--platform=ruby` with `gem install`...

Finally, if any of the window users might reply:

3. What Ruby version are you using?
4. Are you using 64 or 32 bit?
5. Are you building/compiling Eventmachine?
6. If 5, are you doing so with SSL?

Lastly, if anyone wants to use them, gem files for the current master are listed below (built in my fork).  Feel free to use them for local testing.

64 bit:
 https://ci.appveyor.com/api/buildjobs/usvt960ar7tumtn9/artifacts/eventmachine-1.3.0.dev.1-x64-mingw32.gem

32 bit:
https://ci.appveyor.com/api/buildjobs/9cupuxpsa48xv3rx/artifacts/eventmachine-1.3.0.dev.1-x86-mingw32.gem

Also, you can generate the same files on Appveyor if you fork EM...

**Comment by soundasleep** [comment] 2019-01-22 23:57
Hi! I have this problem every time I `bundle update`...

1. What Ruby version are you using?
`ruby 2.5.3p105 (2018-10-18 revision 65156) [x64-mingw32]`


2. Are you using 64 or 32 bit?
64-bit

3. Are you building/compiling Eventmachine?
I'm not sure. I don't think it's compiling but I'm not sure. When I `bundle (update)` the log shows:

```
Fetching eventmachine 1.2.7 (x64-mingw32)
Installing eventmachine 1.2.7 (x64-mingw32)
```

And then the error occurs. I need to `gem uninstall eventmachine` and select the -mingw32 version before I can continue to run anything.

4. If 5, are you doing so with SSL?
This is all on `source 'https://rubygems.org'`

**Comment by MSP-Greg** [comment] 2019-01-23 00:47
@soundasleep 

Thank you for answering the questions.

Bottom line is that the current EventMachine gem (`eventmachine-1.2.7-x64-mingw32`) that is installed by many bundler gemfile configurations is only compatible with Ruby 2.0 thru 2.3.

I suspect a new EventMachine release will happen sometime in the near future, with compatibility with Ruby 2.2 (2.0?) thru 2.6.

If you have to have it now, there is some monkeying around one can do to get it working.  It involves downloading a gem file, installing it as a gem, then copying or symlinking a directory to wherever your app has the EventMachine files.

**Comment by greyskin** [comment] 2019-01-24 22:48
As a side note, if anyone comes across this thread and is having trouble uninstalling eventmachine (I ran into an issue where eventmachine-1.2.7-x64-mingw32 wouldn't uninstall due to dependencies:
`Select gem to uninstall:
 1. eventmachine-1.2.7
 2. eventmachine-1.2.7-x64-mingw32
 3. All versions
> 3
ERROR:  While executing gem ... (Gem::DependencyRemovalException)
    Uninstallation aborted due to dependent gem(s)
Successfully uninstalled eventmachine-1.2.7
`

**Comment by Bonnie-Buyuklieva** [comment] 2021-04-15 20:33
> assuming you have the msys2 openssl package

Hi there.  How do you check for this / install if missing? Thanks!

**Comment by MSP-Greg** [comment] 2021-04-15 20:44
@Bonnie-Buyuklieva

If you're using Ruby 2.4 or later:
```
ridk exec pacman -Q mingw-w64-x86_64-openssl
```
Ruby 2.4 uses OpenSSL 1.0.2, Ruby 2.5 and later uses OpenSSL 1.1.1

**Comment by Bonnie-Buyuklieva** [comment] 2021-04-15 20:59
Thanks @MSP-Greg. I'm on ruby ruby 2.7.2. 

> ridk exec pacman -S mingw-w64-x86_64-openssl
>gem install eventmachine --platform ruby -- --use-system-libraries --with-ssl-dir=c:/msys64/mingw64

**Comment by MSP-Greg** [comment] 2021-04-15 21:10
Does `c:/msys64/mingw64` exist?

Run:
```
ridk version
```

It should show several lines.  Two lines like:
```
msys2:
  path: c:\msys64
```
Whatever that path is, you need to adjust the path in `--with-ssl-dir=c:/msys64/mingw64`

**Comment by Bonnie-Buyuklieva** [comment] 2021-04-15 21:17
The version check was useful to find the path instead of doing it manually. Replacing the path didn't help. 

>ruby -reventmachine -e "puts EM.ssl?" 
[still false]

Could you explain what the above is supposed to do? Thanks!

**Comment by MSP-Greg** [comment] 2021-04-15 21:26
To compile EM with SSL, various header files, etc are needed.  These are installed with the `pacman -S` command.  `--with-ssl-dir` needs to be set correctly for the files to be found.

I'm trying to think what can be amiss.  Of course, my system has `EM.ssl?` as true...

**Comment by MSP-Greg** [comment] 2021-04-15 22:02
@Bonnie-Buyuklieva

What does the following output (my system outputs 'extension'):
```
ruby -reventmachine -e "puts EM.library_type"
```

**Comment by Bonnie-Buyuklieva** [comment] 2021-04-16 09:18
`ruby -reventmachine -e "puts EM.library_type"`
> extension

**Comment by MSP-Greg** [comment] 2021-04-16 15:16
@Bonnie-Buyuklieva

Your compiler works.  Not sure why it's not working.  For **64 bit Ruby 2.5 and later**, one shouldn't need to specify `--with-ssl-dir`.

I did uninstall EventMachine, and reinstall, just to check.

So the following should work (you've already installed MSYS2 OpenSSL, the second step):

```
gem uninstall eventmachine -a
ridk exec pacman -S mingw-w64-x86_64-openssl
gem install eventmachine --platform ruby -- --use-system-libraries
ruby -reventmachine -e "puts EM.ssl?"
```

**Comment by Bonnie-Buyuklieva** [comment] 2021-04-16 15:42
**Got it!**

All the above got me to:
`ruby -reventmachine -e "puts EM.ssl?"`
> true

But when I get back to my project I get:
>Could not find eventmachine-1.2.7-x64-mingw32 in any of the sources
>Run `bundle install` to install missing gems.
`bundle install`
> Bundle complete! X Gemfile dependencies, Y gems now installed.

This takes me to the following error: 
>Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
**Which is solved [here](https://github.com/tabler/tabler/issues/155)**

Hope this helps the next person. Thanks @MSP-Greg !

**Comment by MSP-Greg** [comment] 2021-04-16 21:51
@Bonnie-Buyuklieva

Yeah, bundler is an issue.  If you are ok with compiling every gem in the bundle, the following will install the correct EM:
```
bundle config set --local force_ruby_platform true
```

**Comment by iv-mexx** [comment] 2021-11-09 13:11
> @felicityfmn
> 
> I've installed EM on 2.4, 2.5, & 2.6. Or, if MSYS2 is configured correctly, it should install.
> 
> Try the following (assuming you have the msys2 openssl package):
> 
> ```
> gem install eventmachine --platform ruby -- --use-system-libraries --with-ssl-dir=c:/msys64/mingw64
> 
> C:\>ruby -reventmachine -e "puts EM.ssl?"  => true
> ```

For people on macOS with OpenSSL installed via Homebrew:

0) Uninstall eventmachine `gem uninstall eventmachine --force`
1) Find the location of OpenSSL with `brew info openssl`.  
2) Use that location when installing eventmachine. In my case `gem install eventmachine --platform ruby -- --user-system-libraries --with-ssl-dir=/opt/homebrew/opt/openssl@3`

This worked for me on macOS Monterey with Apple Silicon and Ruby 3.0

**Comment by naxxateux** [comment] 2022-08-11 09:58
> > @felicityfmn
> > I've installed EM on 2.4, 2.5, & 2.6. Or, if MSYS2 is configured correctly, it should install.
> > Try the following (assuming you have the msys2 openssl package):
> > ```
> > gem install eventmachine --platform ruby -- --use-system-libraries --with-ssl-dir=c:/msys64/mingw64
> > 
> > C:\>ruby -reventmachine -e "puts EM.ssl?"  => true
> > ```
> 
> For people on macOS with OpenSSL installed via Homebrew:
> 
> 0. Uninstall eventmachine `gem uninstall eventmachine --force`
> 1. Find the location of OpenSSL with `brew info openssl`.
> 2. Use that location when installing eventmachine. In my case `gem install eventmachine --platform ruby -- --user-system-libraries --with-ssl-dir=/opt/homebrew/opt/openssl@3`
> 
> This worked for me on macOS Monterey with Apple Silicon and Ruby 3.0
> 
> Beware, the location of the OpenSSL library seems to vary across different solutions I've found on the internet, thats why I included Step 1) so you can find the correct location

Thnx so much! Helped me a lot.
