### ISSUE TITLE
Errno::ENOTSOCK An operation was attempted on something that is not a socket.

### ISSUE THREAD

**Issue by pidezhan** [eventmachine/eventmachine#561] opened 2015-01-16 11:39 UTC
I used eventmachine gem as it is required by thin for a Rails application. However, I experienced a couple of issues with the new version 1.0.4.

1. After the first few requests running OK, there was an error "An operation was attempted on something that is not a socket." It appears quite random. Refresh on the same page would work again. But the same problem will come back frequently. 

2. After a while, the error Failed to load resource: net::ERR_EMPTY_RESPONSE would pop up, which rendered the application totally not accessible. 

Rolling back to verison 1.0.3 solves both issues.

Rails version was 3.2.21, Ruby version 1.9.3, on Windows server 2008, 64-bit.

**Comment by ryuta-kai** [comment] 2015-01-17 01:33
I've experienced the same issues and found the cause.
These were introduced by `#define close closesocket` in the commit https://github.com/eventmachine/eventmachine/commit/93ac34d0de1baf218f5c2ca61d39f4230737be7e and will be reproduced by running Apache Benchmark with the following command line:
`ab -k -n 2000 http://127.0.0.1:3000/`

Try this [patch](https://github.com/ryuta-kai/eventmachine/commit/a0022964e549efaa2a6535055583762970fbc064#diff-179dc6925b1f78fb7bd055e8ff4e5b43).

However, I'm not sure whether the patch will work on all versions of Ruby on Windows.

Environments I've confirmed are:
- Windows 8.1 Pro, Windows Server 2012 R2
- RubyInstaller for Windows 1.9.3(32bit), 2.0.0(32bit), 2.1.5(32 and 64bit)
- Rails 3.2.9, 4.1.8
- Thin 1.6.3

**Comment by ccoenen** [comment] 2015-01-18 17:00
I can reproduce the initial Error (Win 7 64bit / Ruby 2.1.5 32bit / EM 1.0.3 / Thin 1.6.3 / Rails 3.2.21). This is my test protocol. I will soon proceed to testing the patch as well.

I do get this error, which loosely translates to roughly the same as @pidezhan's "...sth that is not a socket". *Sidenote* i could only reproduce it without keepalive (no `-k`)  `ab -n 2000 http://127.0.0.1:3000/`. With -k the error never surfaced for me.

**AB-Terminal**

    ab.exe -n 2000 http://127.0.0.1:3000/
    [...]
    Completed 200 requests
    apr_pollset_poll: The timeout specified has expired (70007)
    Total of 388 requests completed

**Thin-Terminal**

    rails s thin
    => Booting Thin
    => Rails 3.2.21 application starting in development on http://0.0.0.0:3000
    => Call with -d to detach
    => Ctrl-C to shutdown server
    Thin web server (v1.6.3 codename Protein Powder)
    Maximum connections set to 1024
    Listening on 0.0.0.0:3000, CTRL+C to stop
    Unexpected error while processing request: Ein Vorgang bezog sich auf ein Objekt, das kein Socket ist. @ fptr_finalize - C:/Users/amenthes/workspace/emtest/public/index.html
            C:/Tools/Ruby21/lib/ruby/gems/2.1.0/gems/rack-1.4.5/lib/rack/file.rb:117:in `close'
            C:/Tools/Ruby21/lib/ruby/gems/2.1.0/gems/rack-1.4.5/lib/rack/file.rb:117:in `open'
            C:/Tools/Ruby21/lib/ruby/gems/2.1.0/gems/rack-1.4.5/lib/rack/file.rb:117:in `each'
            C:/Tools/Ruby21/lib/ruby/gems/2.1.0/gems/thin-1.6.3/lib/thin/response.rb:96:in `each'
            C:/Tools/Ruby21/lib/ruby/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:114:in `post_process'
        C:/Tools/Ruby21/lib/ruby/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:53:in `process'

**Comment by ccoenen** [comment] 2015-01-18 17:26
When installing eventmachine from @ryuta-kai's *windows-patch* branch, i can set ab to fire 20,000 requests at thin without an apparent hiccup. (tried 2 times with 20K requests each).

@pidezhan if you wish to try this patch, you can do so by putting the following line into your Gemfile and running a bundle install:

    gem 'eventmachine', :git => 'https://github.com/ryuta-kai/eventmachine.git', :branch => 'windows-patch'

Then, there's a repo with a Gemfile already referencing that branch: [test-em-561](https://github.com/ccoenen/test-em-561)

**Comment by ccoenen** [comment] 2015-01-18 17:46
I also confirm that this error existed and the patch works on Win 8.1 64bit / Ruby 2.1.3 32bit

That's all the windows machines i have at my disposal, i'm afraid.

**Comment by pidezhan** [comment] 2015-01-19 01:19
@ccoenen I tried to install the patched version by adding the line into my Gemfile, and running `bundle install`, but there was some errors with messages below.

```
Fetching https://github.com/ryuta-kai/eventmachine.git
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Retrying git clone --no-checkout --quiet "D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/cache/bundler/git/eventmachine-e22a7bfc447f01dad1b7066710431
c7c39e1fb28" "D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/bundler/gems/eventmachine-a0022964e549" due to error (2/3): Bundler::Source::Git::GitCom
mandError Git error: command `git clone --no-checkout --quiet "D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/cache/bundler/git/eventmachine-e22a7bfc
447f01dad1b7066710431c7c39e1fb28" "D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/bundler/gems/eventmachine-a0022964e549"` in directory D:/Rails/cprs
_dev has failed.
If this error persists you could try removing the cache directory 'D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/cache/bundler/git/eventmachine-e22a
7bfc447f01dad1b7066710431c7c39e1fb28'
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Retrying git clone --no-checkout --quiet "D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/cache/bundler/git/eventmachine-e22a7bfc447f01dad1b7066710431
c7c39e1fb28" "D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/bundler/gems/eventmachine-a0022964e549" due to error (3/3): Bundler::Source::Git::GitCom
mandError Git error: command `git clone --no-checkout --quiet "D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/cache/bundler/git/eventmachine-e22a7bfc
447f01dad1b7066710431c7c39e1fb28" "D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/bundler/gems/eventmachine-a0022964e549"` in directory D:/Rails/cprs
_dev has failed.
If this error persists you could try removing the cache directory 'D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/cache/bundler/git/eventmachine-e22a
7bfc447f01dad1b7066710431c7c39e1fb28'
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Git error: command `git clone --no-checkout --quiet
"D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/cache/bundler/git/eventmachine-e22a7bfc447f01dad1b7066710431c7c39e1fb28"
"D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/bundler/gems/eventmachine-a0022964e549"`
in directory D:/Rails/cprs_dev has failed.
If this error persists you could try removing the cache directory
'D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/cache/bundler/git/eventmachine-e22a7bfc447f01dad1b7066710431c7c39e1fb28'
```

But there was problem running  `git clone https://github.com/ryuta-kai/eventmachine.git` command. Where could be the problem?

**Comment by sodabrew** [comment] 2015-01-19 05:39
+1 - Based on [ruby bug #9199](https://bugs.ruby-lang.org/issues/9199), this header appears to be part of Ruby's public API. Could you open a PR for the proposed change?

**Comment by sodabrew** [comment] 2015-01-21 01:34
Resolved by b7d9ef87d6535e05bd5ef4ead1abd53f57d987f2

**Closed by sodabrew** 2015-01-21 01:34 UTC

**Comment by jwalkerbg** [comment] 2015-01-27 14:21
When this patched version will be tagged and available to install by *gem install eventmachine* command?

**Comment by sodabrew** [comment] 2015-01-27 19:48
I'm not sure - but in the mean time you can use this in a Gemfile:
`gem 'eventmachine', :github => 'eventmachine/eventmachine', :ref => 'b7d9ef8'`
