### ISSUE TITLE
eventmachine v1.0.7 build fails on Mac OS/X with IRB Ruby 2.2.1: rb_thread_select undeclared

### ISSUE THREAD

**Issue by jez-w** [eventmachine/eventmachine#588] opened 2015-03-25 19:04 UTC
'gem install eventmachine' produces the following errors on Mac OS/X Yosemite 10.10.2, Ruby 2.2.1. This appears to be a similar issue as that for the move to Ruby 2.2 corrected by eventmachine v1.0.4

```
$: uname -v
Darwin Kernel Version 14.1.0: Thu Feb 26 19:26:47 PST 2015; root:xnu-2782.10.73~1/RELEASE_X86_64
$: ruby --version
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]

$: bundle install
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Installing daemons 1.2.2

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/local/bin/ruby -r ./siteconf20150325-2708-t5u8ua.rb extconf.rb 
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... no
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... no
checking for inotify_init() in sys/inotify.h... no
checking for __NR_inotify_init in sys/syscall.h... no
checking for writev() in sys/uio.h... yes
checking for rb_thread_fd_select()... no
checking for rb_fdset_t in ruby/intern.h... yes
checking for rb_wait_for_single_fd()... no
checking for rb_enable_interrupt()... no
checking for rb_time_new()... no
checking for sys/event.h... yes
checking for sys/queue.h... yes
checking for clock_gettime()... no
checking for gethrtime()... no
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling binder.cpp
compiling cmain.cpp
compiling ed.cpp
compiling em.cpp
em.cpp:686:13: error: use of undeclared identifier 'rb_thread_select'; did you mean 'rb_thread_fd_select'?
        if ((ret = rb_thread_select(kqfd + 1, &fdreads, NULL, NULL, &tv)) < 1) {
                   ^~~~~~~~~~~~~~~~
                   rb_thread_fd_select
/usr/local/include/ruby-2.2.0/ruby/intern.h:454:5: note: 'rb_thread_fd_select' declared here
int rb_thread_fd_select(int, rb_fdset_t *, rb_fdset_t *, rb_fdset_t *, struct timeval *);
    ^
em.cpp:686:40: error: cannot initialize a parameter of type 'rb_fdset_t *' with an rvalue of type 'fd_set *'
        if ((ret = rb_thread_select(kqfd + 1, &fdreads, NULL, NULL, &tv)) < 1) {
                                              ^~~~~~~~
/usr/local/include/ruby-2.2.0/ruby/intern.h:454:42: note: passing argument to parameter here
int rb_thread_fd_select(int, rb_fdset_t *, rb_fdset_t *, rb_fdset_t *, struct timeval *);
                                         ^
em.cpp:915:9: error: use of undeclared identifier 'rb_thread_select'; did you mean 'rb_thread_fd_select'?
        return EmSelect (maxsocket+1, &fdreads, &fdwrites, &fderrors, &tv);
               ^~~~~~~~
               rb_thread_fd_select
./em.h:29:22: note: expanded from macro 'EmSelect'
    #define EmSelect rb_thread_select
                     ^
/usr/local/include/ruby-2.2.0/ruby/intern.h:454:5: note: 'rb_thread_fd_select' declared here
int rb_thread_fd_select(int, rb_fdset_t *, rb_fdset_t *, rb_fdset_t *, struct timeval *);
    ^
em.cpp:1039:6: error: use of undeclared identifier 'rb_thread_select'; did you mean 'rb_thread_fd_select'?
                                        EmSelect (0, NULL, NULL, NULL, &tv);
                                        ^~~~~~~~
                                        rb_thread_fd_select
./em.h:29:22: note: expanded from macro 'EmSelect'
    #define EmSelect rb_thread_select
                     ^
/usr/local/include/ruby-2.2.0/ruby/intern.h:454:5: note: 'rb_thread_fd_select' declared here
int rb_thread_fd_select(int, rb_fdset_t *, rb_fdset_t *, rb_fdset_t *, struct timeval *);
    ^
4 errors generated.
Makefile:229: recipe for target 'em.o' failed
make: *** [em.o] Error 1

```

**Comment by jez-w** [comment] 2015-03-27 03:04
I notice that ext/extconf.rb doesn't find rb_wait_for_single_fd(), but this is declared in ruby/io.h

```
$ grep wait_for_single /usr/local/include/ruby-2.2.0/ruby/io.h
int rb_wait_for_single_fd(int fd, int events, struct timeval *tv);
$
```

**Comment by jez-w** [comment] 2015-03-27 03:05
Sorry - clicked on the wrong button

**Comment by tmm1** [comment] 2015-03-27 03:08
Weird, I wonder if the function header moved in 2.2.1?

Can you try this?

``` diff
diff --git a/ext/em.cpp b/ext/em.cpp
index 3bcaa4a..1b4fc34 100644
--- a/ext/em.cpp
+++ b/ext/em.cpp
@@ -132,6 +132,9 @@ EventMachine_t::~EventMachine_t
 
 EventMachine_t::~EventMachine_t()
 {
+	// Clear heartbeats
+	Heartbeats.clear();
+
 	// Run down descriptors
 	size_t i;
 	for (i = 0; i < NewDescriptors.size(); i++)
diff --git a/ext/extconf.rb b/ext/extconf.rb
index c21cdf1..953cb6e 100644
--- a/ext/extconf.rb
+++ b/ext/extconf.rb
@@ -77,7 +77,7 @@ add_define 'HAVE_WRITEV' if have_func('writev', 'sys/uio.h')
 add_define 'HAVE_RB_THREAD_FD_SELECT' if have_func('rb_thread_fd_select')
 add_define 'HAVE_RB_FDSET_T' if have_type('rb_fdset_t', 'ruby/intern.h')
 
-have_func('rb_wait_for_single_fd')
+have_func('rb_wait_for_single_fd', 'ruby/io.h')
 have_func('rb_enable_interrupt')
 have_func('rb_time_new')
 

```

**Comment by theB264** [comment] 2015-04-07 14:48
Does anyone know of a fix for this?  Same issue here.
`Linux 3.13.0-39-generic #66-Ubuntu SMP Tue Oct 28 13:30:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux` `eventmachine (1.0.3)` `ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]`

**Comment by skunkworker** [comment] 2015-04-10 23:14
I was able to fix this by downloading the xcode command line tools for xcode 6.2 on apple's developer server. The ones for 6.3 don't include the right header for some reason.

**Comment by WillSewell** [comment] 2015-04-14 13:58
@skunkworker do you know what libraries are included with the xcode command line tools that got this working? I don't really want to have to download xcode when I don't actually use it.

**Comment by WillSewell** [comment] 2015-04-14 14:05
This seems to be the root cause: http://stackoverflow.com/questions/29529455/missing-c-header-debug-after-updating-osx-command-line-tools-6-3

**Comment by skunkworker** [comment] 2015-04-14 18:24
@WillSewell you don't have to download xcode per se, just the command line utilities for 10.10.2/xcode 6.2. its only about 110mb.

**Comment by WillSewell** [comment] 2015-04-15 18:52
I see. Thanks.

**Comment by maksimf** [comment] 2015-04-21 11:46
Same issue with ruby 2.2.2

**Comment by sodabrew** [comment] 2015-04-24 06:35
Please update to Xcode 6.3.1 and/or Command Line Tools 6.3 with release date of Apr 21, 2015. The original CLT 6.3 was released on Apr 9, 2015.

**Closed by sodabrew** 2015-04-24 06:35 UTC

**Comment by ghost6p** [comment] 2015-10-21 01:31
Ruby 2.2.2, this did it for me.

brew link openssl --force

**Comment by jayfajardo** [comment] 2015-10-21 12:54
`brew link openssl --force` did it for me too

**Comment by jjuarez** [comment] 2015-10-22 22:41
Unfortunately the homebrew workaround did not work for me :/ I'm trying to install eventmachine version 1.0.8 over ruby 2.2.3 on OSx 10.11.1 with command line tools Command_Line_Tools_OS_X_10.11_for_Xcode_7.1

**Comment by sdlovecraft** [comment] 2015-10-28 02:59
brew link openssl --force , did the trick for me too

**Comment by Focinfi** [comment] 2015-10-31 00:21
`brew link openssl --force` works for me (Mac OS 10.11.1  Ruby 2.2.1)

**Comment by san983** [comment] 2015-10-31 22:18
`brew link openssl --force` also worked for me :+1:

**Comment by sebabouche** [comment] 2015-11-08 17:55
brew link openssl --force worked !

**Comment by chamnap** [comment] 2015-12-03 08:04
(y)

**Comment by monyprak** [comment] 2015-12-04 04:26
(y)

**Comment by simleap** [comment] 2015-12-08 04:24
it worked! thanks

**Comment by sodabrew** [comment] 2015-12-08 06:15
I am locking this issue. The posted solution is probably not a good one, because it overrides the system OpenSSL library with HomeBrew's library. Further discussion in #661 to find a better alternative for a forthcoming release that will work automatically on El Capitan.

**Comment by sodabrew** [comment] 2016-01-13 09:01
Regarding the El Capitan / OpenSSL issues, please try eventmachine-1.0.9, it should compile and install without error now.
