### ISSUE TITLE
Symbol not found: __ZNSt8ios_base4InitD1Ev

### ISSUE THREAD

**Issue by bartoszkopinski** [eventmachine/eventmachine#613] opened 2015-07-19 15:06 UTC
This is what I get when I run the `bundle exec rake` command:
```shell
mkdir -p tmp/x86_64-darwin14.0/rubyeventmachine/2.2.2
cd tmp/x86_64-darwin14.0/rubyeventmachine/2.2.2
/.rvm/rubies/ruby-2.2.2/bin/ruby -I. ../../../../ext/extconf.rb
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... no
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for inotify_init() in sys/inotify.h... no
checking for __NR_inotify_init in sys/syscall.h... no
checking for writev() in sys/uio.h... yes
checking for rb_thread_fd_select()... yes
checking for rb_fdset_t in ruby/intern.h... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... no
checking for rb_time_new()... yes
checking for sys/event.h... yes
checking for sys/queue.h... yes
checking for clock_gettime()... no
checking for gethrtime()... no
creating Makefile
cd -
cd tmp/x86_64-darwin14.0/rubyeventmachine/2.2.2
make
compiling ../../../../ext/binder.cpp
compiling ../../../../ext/cmain.cpp
compiling ../../../../ext/ed.cpp
compiling ../../../../ext/em.cpp
compiling ../../../../ext/kb.cpp
compiling ../../../../ext/page.cpp
compiling ../../../../ext/pipe.cpp
compiling ../../../../ext/rubymain.cpp
compiling ../../../../ext/ssl.cpp
linking shared-object rubyeventmachine.bundle
cd -
install -c tmp/x86_64-darwin14.0/rubyeventmachine/2.2.2/rubyeventmachine.bundle lib/rubyeventmachine.bundle
mkdir -p tmp/x86_64-darwin14.0/fastfilereaderext/2.2.2
cd tmp/x86_64-darwin14.0/fastfilereaderext/2.2.2
/.rvm/rubies/ruby-2.2.2/bin/ruby -I. ../../../../ext/fastfilereader/extconf.rb
creating Makefile
cd -
cd tmp/x86_64-darwin14.0/fastfilereaderext/2.2.2
make
compiling ../../../../ext/fastfilereader/mapper.cpp
compiling ../../../../ext/fastfilereader/rubymain.cpp
linking shared-object fastfilereaderext.bundle
cd -
install -c tmp/x86_64-darwin14.0/fastfilereaderext/2.2.2/fastfilereaderext.bundle lib/fastfilereaderext.bundle
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
/ruby/eventmachine/lib/eventmachine.rb:8:in `require': dlopen(/ruby/eventmachine/lib/rubyeventmachine.bundle, 9): Symbol not found: __ZNSt8ios_base4InitD1Ev (LoadError)
  Referenced from: /ruby/eventmachine/lib/rubyeventmachine.bundle
  Expected in: flat namespace
 in /ruby/eventmachine/lib/rubyeventmachine.bundle - /ruby/eventmachine/lib/rubyeventmachine.bundle
  from /ruby/eventmachine/lib/eventmachine.rb:8:in `<top (required)>'
  from /ruby/eventmachine/tests/em_test_helper.rb:1:in `require'
  from /ruby/eventmachine/tests/em_test_helper.rb:1:in `<top (required)>'
  from /ruby/eventmachine/tests/test_attach.rb:1:in `require'
  from /ruby/eventmachine/tests/test_attach.rb:1:in `<top (required)>'
  from /.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/rake_test_loader.rb:10:in `require'
  from /.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/rake_test_loader.rb:10:in `block (2 levels) in <main>'
  from /.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/rake_test_loader.rb:9:in `each'
  from /.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/rake_test_loader.rb:9:in `block in <main>'
  from /.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/rake_test_loader.rb:4:in `select'
  from /.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -w -I"lib:tests:lib" -I"/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0" "/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/rake_test_loader.rb" "tests/**/test_*.rb" ]
/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```

This is my `RbConfig::CONFIG` output:
```ruby
2.2.2 :001 > RbConfig::CONFIG
 => {
  "DESTDIR"=>"",
  "MAJOR"=>"2",
  "MINOR"=>"2",
  "TEENY"=>"0",
  "PATCHLEVEL"=>"95",
  "INSTALL"=>"/usr/bin/install -c",
  "EXEEXT"=>"",
  "prefix"=>"/.rvm/rubies/ruby-2.2.2",
  "ruby_install_name"=>"ruby",
  "RUBY_INSTALL_NAME"=>"ruby",
  "RUBY_SO_NAME"=>"ruby.2.2.0",
  "exec"=>"exec",
  "ruby_pc"=>"ruby-2.2.pc",
  "PACKAGE"=>"ruby",
  "BUILTIN_TRANSSRCS"=>" newline.c",
  "USE_RUBYGEMS"=>"YES",
  "MANTYPE"=>"doc",
  "NROFF"=>"/usr/bin/nroff",
  "vendorarchhdrdir"=>"/.rvm/rubies/ruby-2.2.2/include/ruby-2.2.0/vendor_ruby/x86_64-darwin14.0",
  "sitearchhdrdir"=>"/.rvm/rubies/ruby-2.2.2/include/ruby-2.2.0/site_ruby/x86_64-darwin14.0",
  "rubyarchhdrdir"=>"/.rvm/rubies/ruby-2.2.2/include/ruby-2.2.0/x86_64-darwin14.0",
  "vendorhdrdir"=>"/.rvm/rubies/ruby-2.2.2/include/ruby-2.2.0/vendor_ruby",
  "sitehdrdir"=>"/.rvm/rubies/ruby-2.2.2/include/ruby-2.2.0/site_ruby",
  "rubyhdrdir"=>"/.rvm/rubies/ruby-2.2.2/include/ruby-2.2.0",
  "RUBY_SEARCH_PATH"=>"",
  "UNIVERSAL_INTS"=>"",
  "UNIVERSAL_ARCHNAMES"=>"",
  "configure_args"=>" '--prefix=/.rvm/rubies/ruby-2.2.2' '' '--with-opt-dir=/usr/local/opt/libyaml:/usr/local/opt/readline:/usr/local/opt/libksba:/usr/local/opt/openssl' '--disable-install-doc' '--enable-shared' 'build_alias=' 'host_alias=' 'target_alias=' 'CC=gcc'",
  "vendorarchdir"=>"/.rvm/rubies/ruby-2.2.2/lib/ruby/vendor_ruby/2.2.0/x86_64-darwin14.0",
  "vendorlibdir"=>"/.rvm/rubies/ruby-2.2.2/lib/ruby/vendor_ruby/2.2.0",
  "vendordir"=>"/.rvm/rubies/ruby-2.2.2/lib/ruby/vendor_ruby",
  "sitearchdir"=>"/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/x86_64-darwin14.0",
  "sitelibdir"=>"/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0",
  "sitedir"=>"/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby",
  "rubyarchdir"=>"/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/x86_64-darwin14.0",
  "rubylibdir"=>"/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0",
  "ruby_version"=>"2.2.0",
  "sitearch"=>"x86_64-darwin14.0",
  "arch"=>"x86_64-darwin14.0",
  "sitearchincludedir"=>"/.rvm/rubies/ruby-2.2.2/include/x86_64-darwin14.0",
  "archincludedir"=>"/.rvm/rubies/ruby-2.2.2/include/x86_64-darwin14.0",
  "sitearchlibdir"=>"/.rvm/rubies/ruby-2.2.2/lib/x86_64-darwin14.0",
  "archlibdir"=>"/.rvm/rubies/ruby-2.2.2/lib/x86_64-darwin14.0",
  "libdirname"=>"libdir",
  "RUBY_EXEC_PREFIX"=>"/.rvm/rubies/ruby-2.2.2",
  "RUBY_LIB_VERSION"=>"",
  "RUBY_LIB_VERSION_STYLE"=>"3\t/* full */",
  "RI_BASE_NAME"=>"ri",
  "ridir"=>"/.rvm/rubies/ruby-2.2.2/share/ri",
  "rubysitearchprefix"=>"/.rvm/rubies/ruby-2.2.2/lib/ruby/x86_64-darwin14.0",
  "rubyarchprefix"=>"/.rvm/rubies/ruby-2.2.2/lib/ruby/x86_64-darwin14.0",
  "MAKEFILES"=>"Makefile GNUmakefile",
  "PLATFORM_DIR"=>"",
  "THREAD_MODEL"=>"pthread",
  "SYMBOL_PREFIX"=>"_",
  "EXPORT_PREFIX"=>"",
  "COMMON_HEADERS"=>"",
  "COMMON_MACROS"=>"",
  "COMMON_LIBS"=>"",
  "MAINLIBS"=>"",
  "ENABLE_SHARED"=>"yes",
  "DLDLIBS"=>"",
  "SOLIBS"=>"-lpthread -ldl -lobjc",
  "LIBRUBYARG_SHARED"=>"-lruby.2.2.0",
  "LIBRUBYARG_STATIC"=>"-lruby.2.2.0-static -framework CoreFoundation",
  "LIBRUBYARG"=>"-lruby.2.2.0",
  "LIBRUBY"=>"libruby.2.2.0.dylib",
  "LIBRUBY_ALIASES"=>"libruby.2.2.dylib libruby.dylib",
  "LIBRUBY_SO"=>"libruby.2.2.0.dylib",
  "LIBRUBY_A"=>"libruby.2.2.0-static.a",
  "RUBYW_INSTALL_NAME"=>"",
  "rubyw_install_name"=>"",
  "EXTDLDFLAGS"=>"",
  "EXTLDFLAGS"=>"",
  "strict_warnflags"=>"",
  "warnflags"=>"-Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wshorten-64-to-32 -Wimplicit-function-declaration -Wdivision-by-zero -Wdeprecated-declarations -Wextra-tokens",
  "debugflags"=>"-ggdb3",
  "optflags"=>"-O3 -fno-fast-math",
  "cxxflags"=>" -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wshorten-64-to-32 -Wimplicit-function-declaration -Wdivision-by-zero -Wdeprecated-declarations -Wextra-tokens",
  "cflags"=>" -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wshorten-64-to-32 -Wimplicit-function-declaration -Wdivision-by-zero -Wdeprecated-declarations -Wextra-tokens",
  "cppflags"=>"",
  "NULLCMD"=>":",
  "DLNOBJ"=>"dln.o",
  "INSTALLDOC"=>"nodoc",
  "CAPITARGET"=>"nodoc",
  "RDOCTARGET"=>"nodoc",
  "DTRACE_REBUILD"=>"",
  "DTRACE_OBJ"=>"",
  "DTRACE_EXT"=>"d",
  "EXECUTABLE_EXTS"=>"",
  "ARCHFILE"=>"",
  "LIBRUBY_RELATIVE"=>"no",
  "EXTOUT"=>".ext",
  "RUNRUBY_COMMAND"=>"$(MINIRUBY) $(srcdir)/tool/runruby.rb --extout=.ext $(RUNRUBYOPT)",
  "PREP"=>"miniruby",
  "BTESTRUBY"=>"$(MINIRUBY)",
  "CROSS_COMPILING"=>"no",
  "TEST_RUNNABLE"=>"yes",
  "rubylibprefix"=>"/.rvm/rubies/ruby-2.2.2/lib/ruby",
  "setup"=>"Setup",
  "ENCSTATIC"=>"",
  "EXTSTATIC"=>"",
  "STRIP"=>"strip -A -n",
  "TRY_LINK"=>"",
  "LIBPATHENV"=>"DYLD_LIBRARY_PATH",
  "RPATHFLAG"=>"",
  "LIBPATHFLAG"=>" -L%s",
  "LINK_SO"=>"\ntest -z '$(RUBY_CODESIGN)' || codesign -s '$(RUBY_CODESIGN)' -f $@",
  "ASMEXT"=>"S",
  "LIBEXT"=>"a",
  "DLEXT2"=>"",
  "DLEXT"=>"bundle",
  "LDSHAREDXX"=>"g++ -dynamic -bundle",
  "LDSHARED"=>"gcc -dynamic -bundle",
  "CCDLFLAGS"=>"-fno-common",
  "STATIC"=>"",
  "ARCH_FLAG"=>"",
  "DLDFLAGS"=>"-Wl,-undefined,dynamic_lookup -Wl,-multiply_defined,suppress -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib ",
  "ALLOCA"=>"",
  "codesign"=>"codesign",
  "POSTLINK"=>"test -z '$(RUBY_CODESIGN)' || codesign -s '$(RUBY_CODESIGN)' -f $@",
  "WERRORFLAG"=>"-Werror",
  "CHDIR"=>"cd -P",
  "RMALL"=>"rm -fr",
  "RMDIRS"=>"rmdir -p",
  "RMDIR"=>"rmdir",
  "CP"=>"cp",
  "RM"=>"rm -f",
  "PKG_CONFIG"=>"pkg-config",
  "PYTHON"=>"",
  "DOXYGEN"=>"",
  "DOT"=>"",
  "DTRACE"=>"dtrace",
  "MAKEDIRS"=>"mkdir -p",
  "MKDIR_P"=>"mkdir -p",
  "INSTALL_DATA"=>"/usr/bin/install -c -m 644",
  "INSTALL_SCRIPT"=>"/usr/bin/install -c",
  "INSTALL_PROGRAM"=>"/usr/bin/install -c",
  "SET_MAKE"=>"",
  "LN_S"=>"ln -s",
  "NM"=>"nm",
  "DLLWRAP"=>"",
  "WINDRES"=>"",
  "OBJCOPY"=>":",
  "OBJDUMP"=>"",
  "ASFLAGS"=>"",
  "AS"=>"as",
  "AR"=>"ar",
  "RANLIB"=>"ranlib",
  "try_header"=>"",
  "CC_VERSION"=>"gcc -v",
  "COUTFLAG"=>"-o ",
  "OUTFLAG"=>"-o ",
  "CPPOUTFILE"=>"-o conftest.i",
  "GNU_LD"=>"no",
  "LD"=>"ld",
  "GCC"=>"yes",
  "EGREP"=>"/usr/bin/grep -E",
  "GREP"=>"/usr/bin/grep",
  "CPP"=>"gcc -E",
  "CXXFLAGS"=>" -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wshorten-64-to-32 -Wimplicit-function-declaration -Wdivision-by-zero -Wdeprecated-declarations -Wextra-tokens",
  "OBJEXT"=>"o",
  "CPPFLAGS"=>" -I/usr/local/opt/libyaml/include -I/usr/local/opt/readline/include -I/usr/local/opt/libksba/include -I/usr/local/opt/openssl/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT  ",
  "LDFLAGS"=>"-L. -fstack-protector -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib ",
  "CFLAGS"=>" -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wshorten-64-to-32 -Wimplicit-function-declaration -Wdivision-by-zero -Wdeprecated-declarations -Wextra-tokens  -fno-common -pipe",
  "CXX"=>"g++",
  "CC"=>"gcc",
  "NACL_LIB_PATH"=>"",
  "NACL_SDK_VARIANT"=>"",
  "NACL_SDK_ROOT"=>"",
  "NACL_TOOLCHAIN"=>"",
  "target_os"=>"darwin14.0",
  "target_vendor"=>"apple",
  "target_cpu"=>"x86_64",
  "target"=>"x86_64-apple-darwin14.0",
  "host_os"=>"darwin14.3.0",
  "host_vendor"=>"apple",
  "host_cpu"=>"x86_64",
  "host"=>"x86_64-apple-darwin14.3.0",
  "RUBY_VERSION_NAME"=>"ruby-2.2.0",
  "RUBYW_BASE_NAME"=>"rubyw",
  "RUBY_BASE_NAME"=>"ruby",
  "build_os"=>"darwin14.3.0",
  "build_vendor"=>"apple",
  "build_cpu"=>"x86_64",
  "build"=>"x86_64-apple-darwin14.3.0",
  "RUBY_PROGRAM_VERSION"=>"2.2.2",
  "HAVE_BASERUBY"=>"yes",
  "target_alias"=>"",
  "host_alias"=>"",
  "build_alias"=>"",
  "LIBS"=>"-lpthread -ldl -lobjc",
  "ECHO_T"=>"",
  "ECHO_N"=>"",
  "ECHO_C"=>"\\\\c",
  "DEFS"=>"",
  "mandir"=>"/.rvm/rubies/ruby-2.2.2/share/man",
  "localedir"=>"/.rvm/rubies/ruby-2.2.2/share/locale",
  "libdir"=>"/.rvm/rubies/ruby-2.2.2/lib",
  "psdir"=>"/.rvm/rubies/ruby-2.2.2/share/doc/ruby",
  "pdfdir"=>"/.rvm/rubies/ruby-2.2.2/share/doc/ruby",
  "dvidir"=>"/.rvm/rubies/ruby-2.2.2/share/doc/ruby",
  "htmldir"=>"/.rvm/rubies/ruby-2.2.2/share/doc/ruby",
  "infodir"=>"/.rvm/rubies/ruby-2.2.2/share/info",
  "docdir"=>"/.rvm/rubies/ruby-2.2.2/share/doc/ruby",
  "oldincludedir"=>"/usr/include",
  "includedir"=>"/.rvm/rubies/ruby-2.2.2/include",
  "localstatedir"=>"/.rvm/rubies/ruby-2.2.2/var",
  "sharedstatedir"=>"/.rvm/rubies/ruby-2.2.2/com",
  "sysconfdir"=>"/.rvm/rubies/ruby-2.2.2/etc",
  "datadir"=>"/.rvm/rubies/ruby-2.2.2/share",
  "datarootdir"=>"/.rvm/rubies/ruby-2.2.2/share",
  "libexecdir"=>"/.rvm/rubies/ruby-2.2.2/libexec",
  "sbindir"=>"/.rvm/rubies/ruby-2.2.2/sbin",
  "bindir"=>"/.rvm/rubies/ruby-2.2.2/bin",
  "exec_prefix"=>"/.rvm/rubies/ruby-2.2.2",
  "PACKAGE_URL"=>"",
  "PACKAGE_BUGREPORT"=>"",
  "PACKAGE_STRING"=>"",
  "PACKAGE_VERSION"=>"",
  "PACKAGE_TARNAME"=>"",
  "PACKAGE_NAME"=>"",
  "PATH_SEPARATOR"=>":",
  "SHELL"=>"/bin/sh",
  "archdir"=>"/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/x86_64-darwin14.0",
  "topdir"=>"/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/x86_64-darwin14.0"}
```

And `gcc` version:
```shell
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```
But I get the same error when I switch to this version:
```shell
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.0.57.2)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```

I tried everything - different ruby versions, reinstalling ruby, rvm, upgrading osx to 10.11, changing `CONFIG['CC']` and `CONFIG['CCX']` to clang, and now I'm hopeless because I can't use anything that has eventmachine in it. `em/pure_ruby` it's not always an option.

Any ideas?

**Comment by sodabrew** [comment] 2015-07-30 12:12
Which version of the Command Line Tools do you have?

**Comment by bartoszkopinski** [comment] 2015-07-30 13:26
@sodabrew 7.0

**Comment by sodabrew** [comment] 2015-07-30 13:39
CLT 7.0 must be beta for El Capitan? Did you have the same problem with Yosemite and CLT 6.4?

**Comment by bartoszkopinski** [comment] 2015-07-30 13:41
@sodabrew Yes, I've had this problem too before upgrading.

**Comment by sodabrew** [comment] 2015-08-11 01:08
Could you try again with current master? I will also set up a Ruby 2.2.2 locally on my Mac shortly.

**Comment by bartoszkopinski** [comment] 2015-08-18 11:25
@sodabrew I'm getting the same error with current master

**Comment by sodabrew** [comment] 2016-02-11 18:56
I still cannot reproduce this problem.

**Comment by sodabrew** [comment] 2016-04-08 06:32
Closing because I cannot reproduce the issue and don't have much else to go on at this point.

**Closed by sodabrew** 2016-04-08 06:32 UTC
